@echo off

nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmScriptSettingsPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmScriptSettingsPkg_default.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\IfElsePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ResolutionPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmSettingsPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmSettingsPkg_default.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\NamePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\NameStorePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\SetGetBoundedGenericPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\SetGetBoundedPkg_Instances.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\TranscriptBasePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmGlobalPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\TextUtilPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\FileUtilPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\LanguageSupport2019Pkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\AssertApiPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\AlertLogPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\TbUtilPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\SortListPkg_int.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\RandomBasePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\RandomProcedurePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmTypesPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\RandomPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MessageListPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\CoverageVendorApiPkg_NVC.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\CoverageVendorApiPkg_default.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\TranscriptPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\RandomPkg2019.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardGenericPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardPkg_int.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardPkg_IntV.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardPkg_signed.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardPkg_slv.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ScoreboardPkg_unsigned.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MemorySupportPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MemoryGenericPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MemoryPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MemoryPkgIs01.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\CoveragePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\CoveragePtPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\DelayCoveragePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ClockResetPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ReportPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\ResizePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\FileLinePathPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\IdFifoPtPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\DynamicVectorGenericPkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\DynamicVectorPkg_instances.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\MessagePkg.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmContext.vhd
nvc --work=osvvm --std=2019 -a .\osvvm_library\OsvvmTestCommonPkg_default.vhd